name: location_alarm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3  # database
  path_provider: ^2.0.1 # database file path
  flutter_riverpod: ^1.0.0-dev.5 # state management
  freezed_annotation: ^0.14.2 # class build etc
  google_maps_flutter: ^2.0.6 # google map function
  geolocator: ^7.4.0 # device location
  dartz: ^0.10.0 # either<failure,success>
  geocoding: ^2.0.0 # placemarks
  background_location: ^0.6.1 # background location when screen is off
  flutter_ringtone_player: ^3.0.0 # alarm ringtone
  shared_preferences: ^2.0.7 # cache for alarm type selection
  permission_handler: ^8.1.4+2 # handle permission status
  flutter_vibrate: ^1.1.0 # device vibration
  flutter_screenutil: ^5.0.0+2 # app responsiveness
  flutter_google_places: ^0.3.0 # google places api autocomplete
  uuid: ^3.0.4 # generate session token
  http: ^0.13.3 # make http requests to get autocomplete suggestions 
  package_info_plus_web: ^1.0.4 # fix missing package for generated_plugin_registrant?
  geocoder: ^0.2.1 # get address latlng to move camera
  country_codes: ^2.0.0 # get country code for google autocomplete suggestions

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  freezed: ^0.14.1
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
